web:
  extends:
    file: docker/compose-common.yml
    service: web
  volumes:
    - .:/portus
  links:
    - db
  command: thin start

db:
  image: opensuse/mariadb
  environment:
    MYSQL_USER: portus
    MYSQL_PASS: portus

registry:
  extends:
    file: docker/compose-common.yml
    service: registry
  volumes:
    - docker/registry:/registry
  entrypoint: /registry/entry.sh
  env_file: docker/environment
  links:
    - web
